[versions]
agp = "8.13.2"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "34"
androidx-activityCompose = "1.12.2"
androidx-lifecycle = "2.9.6"
compose-plugin = "1.9.3"
kotlin = "2.3.0"
orbit = "11.0.0"
kodein = "7.30.0"
ktor = "3.3.3"
room = "2.8.4"
sqlite = "2.6.2"
kotlinx-datetime = "0.7.1"
ksp = "2.3.0"
datastore = "1.2.0"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
orbit-core = { module = "org.orbit-mvi:orbit-core", version.ref = "orbit" }
kodein-di = { module = "org.kodein.di:kodein-di", version.ref = "kodein" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
ktor-client-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }

yandex-appmetrica = { module = "io.appmetrica.analytics:analytics", version = "7.6.0" }
google-firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics", version = "19.4.0" }

nsexception = { module = "com.rickclephas.kmp:nsexception-kt-core", version = "1.0.0-BETA-8" }

kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-sqliteBundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }

androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version = "4.4.4" }
firebaseCrashlytics = { id = "com.google.firebase.crashlytics", version = "3.0.6" }
room = { id = "androidx.room", version.ref = "room" }
googleDevtoolsKsp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }